### ISSUE TITLE
Question Web Module

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Dev#1]
Written there have been changes to 
- Adds functionality for the HTML pages 

do not tell what has been added or changed

**Comment by emperorstarfinder** [comment]
It actually means what Irishwolf has said. He has added in the WebServer that will run the HTML pages.  Keep in mind we are still porting code that will be in the base code for Version 1.0.3 so you will see that kind of message for a time on commits.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
Another question, this module is compatible with the server version 1.0.2

**Comment by emperorstarfinder** [comment]
Please keep in mind that the Virtual-Dev repository is for development purposes for the next version.  It is strongly recommended that for production level grids you please use the stable version in the Virtual-Universe repository as the development repository may have many bugs as it works its way through the development process.

This module is already in the main Virtual-Universe repository and already works on Version 1.0.2 RC2. As code is added to this repository it is being reviewed and cleaned up to be sure the code is clean.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as this has been answered and no further activity has occurred.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
