### ISSUE TITLE
Erorrs compiling

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Dev#22]
Erorrs compiling 

### Steps to reproduce

1. http://prntscr.com/chdn34
2. http://prntscr.com/chdn9f

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Server configuration

**Operating system**: Windows 7(32bit) AND Windows Server 2012 (64bit)

**Web server:**

**Database:**

**Virtual Universe version:** 1.0.3

### Logs

Please make sure that Virtual Universe has made an log-file and include a link to it here

**Comment by emperorstarfinder** [comment]
Good catch, its all fixed now thanks.

I also see your using the old runprebuild.bat on windows.  For building on Windows use the runprebuild2015.bat to compile and Visual Studios 2015 to build.

**Comment by LifeGold** [comment]
Work. 

Following issue.

When you create a region that produces here, and about oar saving gives error because of this
http://prntscr.com/chnyzs

**Comment by emperorstarfinder** [comment]
It is possible that this could be the OAR itself.  Usually when it is yellow text it is just a warning and not necessarily an error.  NullReferenceException usually indicates something is missing.  In this case it is probably a texture that is missing from the OAR.  Recommendation would be to try another OAR you know is working correctly and see if the error reproduces.  If so please reference the screenshot you reference here along with the error provided by the other OAR in a new issue.  This way we don't get issues confused as these are not related to the original problem reported in this issue.  Also by putting it its own issue ticket will allow us to keep a better internal record and tracking of what issues are still current and which ones we have fixed.

**Comment by emperorstarfinder** [comment]
We have confirmed the warnign you received relating to issues with worldmap and loading region textures.  See Issue #24
