### ISSUE TITLE
Error when creating region

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Dev#24]
### Notice

**If you are using WhiteCore-Sim please do not submit an issue report to Virtual Universe as we are unable to assist you.  Any issues reported to Virtual Universe which involve your use of WhiteCore-Sim will immediately be closed and you will be referred to WhiteCore-Sim.**

**In addition please do not submit issue reports regarding Virtual Universe to the WhiteCore-Sim issues tracker as they cannot help you and they will be immediately closed and you will be referred to Virtual Universe**

### Notice 2

**Effective August 1, 2016 - Any issues opened which do not have the provided questions answered will be closed immediately without further action.  The questions need to be answered to help provide us with as much information as possible to fix the bugs you find.  This has nothing to do with disliking reports or any individuals.  This has to do with getting to the root of the issues you report.  Thank you.**

### Issue Type

| Question      | Answer
| ------------- | ---------
| Bug?          | [yes]
| New feature?  | [no]

### For Feature requests please answer the following

**Describe the feature you are requesting**:

**Has the feature been implemented by a similar project**:

**What other project similar to Virtual Universe has implemented the feature**:

**URL to where we can view the feature and or source code**:

### NOTE About Features

**The Second Galaxy Development Team will consider the features after we have seen enough interest by users of Virtual Universe.  The Feature must recieve at least five (5) core developers voting in favor of the feature for it to be included in a future release.**

### Steps to reproduce

1. Create new region
2.
3.

### Expected behaviour

Everything should load as normal

### Actual behaviour

http://prntscr.com/chnyzs

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**Virtual Universe version:**

### Logs

NOTE: This issue was reported by LifeGold in a different unrelated issue.

Please make sure that Virtual Universe has made an log-file and include a link to it here

**Comment by emperorstarfinder** [comment]
This has been confirmed

**Comment by emperorstarfinder** [comment]
Further testing indicates the region is loading properly without problems.  The warning is likely a false warning and not something to worry about.  verified by logging in to the world and world map.  However it will need to be addressed so it does not keep reappearing on the consoles.

**Comment by LifeGold** [comment]
@emperorstarfinder He creates it, but do not save it in Oar

**Comment by emperorstarfinder** [comment]
I will be investigating this issue further today as I am quite sure there is an issue, but I am just not sure what the actual issue is as of yet.

**Comment by emperorstarfinder** [comment]
We have a major fix upcoming that will fix this issue.  We expect this to be rolled into the repositories later in the day USA Eastern Standard Time

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
Fixed thank you

**Comment by emperorstarfinder** [comment]
Closing as user reports issue resolved

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
