### ISSUE TITLE
Load IAR

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Dev#26]
The problem with the download of IAR did everything as you once wrote to me, but alas not ship them. Writes that ARI not found.  Created in the Data folder UserArchives folder and threw back his IAR file.

http://prntscr.com/ci4bfl

**Comment by emperorstarfinder** [comment]
We have a major fix upcoming that will fix this issue.  We expect this to be rolled into the repositories later in the day USA Eastern Standard Time

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Okay one way to be sure its saving the IARs correctly in the right folders is to simply do the save iar command in the grid console.  This will allow the system to create the folder properly in the Data folder and itll save an IAR.  then you can copy IARs you want to import into that folder and it should find them.  Other then that the other potential issue would be the spelling your giving it in the console not being correct (matching what the exact name and spelling of the name of the iar file is).

I have tested there isn't an issue with importing/exporting IARs that is apparent.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
Work thank you

**Comment by emperorstarfinder** [comment]
Closing as user reports issue resolved

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
