### ISSUE TITLE
An infinite number of items can be worn on the arm.

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Dev#27]
I will not write much old problem, already passed it.

https://github.com/Virtual-Universe/Virtual-Universe/issues/11

solution to problem

https://github.com/Virtual-Universe/Virtual-Universe/commit/a1c514a23105c1f517d35a7eb00609fef9352417

**Comment by emperorstarfinder** [comment]
We have a major fix upcoming that will fix this issue.  We expect this to be rolled into the repositories later in the day USA Eastern Standard Time

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
This bug does seem to have made its way back into the code.  I will correct this once i correct another problem that has been found relating to attachments and avatars.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by QueenStarfinder** [comment]
I have pushed a fix to this to repo for @emperorstarfinder as he is having troubles with his git connection.  This should now be resolved for the moment.

**Comment by emperorstarfinder** [comment]
Closing as this has been resolved.  To fix the user must configure the ini file correctly.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
