### ISSUE TITLE
Known Issues To-Do List

### ISSUE THREAD

**Issue by DevilStarfinder** [Virtual-Universe/Virtual-Dev#29]
DisplayNames update Time Resets after a GridServer Restart

Need to assign this to the Database instead of Saving it in the Memory.

So for now i advice turning the feature of in the DisplayNames.ini

Submitting a AbuseReport throws a warning but does not infect functionality.

NOTE: This will be corrected after the upcoming major commit.

**Comment by emperorstarfinder** [comment]
This is a known bug to the development team.  No further reporting on this bug is needed.

**Comment by emperorstarfinder** [comment]
Closing as I have added this to the projects list.  This fix should be dealt with now as quickly as possible.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
