### ISSUE TITLE
MaxThreadCount = 50 in DNE / VirtualScript is this correct or should it be 100?

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Dev#33]
### Notice

**If you are using WhiteCore-Sim please do not submit an issue report to Virtual Universe as we are unable to assist you.  Any issues reported to Virtual Universe which involve your use of WhiteCore-Sim will immediately be closed and you will be referred to WhiteCore-Sim.**

**In addition please do not submit issue reports regarding Virtual Universe to the WhiteCore-Sim issues tracker as they cannot help you and they will be immediately closed and you will be referred to Virtual Universe**

### Notice 2

**Effective August 1, 2016 - Any issues opened which do not have the provided questions answered will be closed immediately without further action.  The questions need to be answered to help provide us with as much information as possible to fix the bugs you find.  This has nothing to do with disliking reports or any individuals.  This has to do with getting to the root of the issues you report.  Thank you.**

### Issue Type

| Question      | Answer
| ------------- | ---------
| Bug?          | [no]
| New feature?  | [no]

### Question

Both VirtualScript and DotNetEngine (For Upstream-Provider-WhiteCore) have a default coded MaxThreadCount - 100 however the ini file has it set at 50.  Which one is really the correct setting for MaxTHreadCount and is there some residual effects for Windows, Linux, and Mac OS X?

**Comment by BritanyannStarfinder** [comment]
Good morning,

To answer this I had to review Opensim source code, Aurora-Sim source code, and Upstream-WhiteCore's source code.  It is a carry over from Opensim 0.6.3 and was likely changed in Aurora-Sim in the engine code but forgotten in the configuration file.  No Evidence to suggest that it got changed in Upstream-WhiteCore.  For Upstream-WhiteCore devs please see Virtual-Dev commit: https://github.com/Virtual-Universe/Virtual-Dev/commit/002a8df86fee4954138989b2b8beef7852ab0902 for suggested notation to add to the configuration file.  There appears to be no issue setting the MaxThreadCount to 100 in the ini file.

Hope it helps

Britanyann Starfinder
Core Developer
Scripting Engine Developer
Work Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team
