### ISSUE TITLE
Error after build with mono 5 under linuxmint

### ISSUE THREAD

**Issue by BogusCurry** [Virtual-Universe/Virtual-Dev#43]
Hi ;)
I have build the actual devrepo with mono 5, after build comes this build

https://paste.md-5.net/gavupiqoda.coffee

System LinuxMint 18.1 64bit local not Server
Mono 5 
with autobuild.sh

Greetings
Bogus Curry
Founder and hoster from GridTalk.de
`

**Comment by emperorstarfinder** [comment]
Hmmm.

Simple fix just a missing icon for the web server.  I'll fix that shortly.  Thanks for letting us know.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by emperorstarfinder** [comment]
Fixed, Let us know if it works.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by BogusCurry** [comment]
Is fixed  thanks ;D

Have a nice Day ;D

**Comment by emperorstarfinder** [comment]
Closing

User reports this issue has been resolved.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com
