### ISSUE TITLE
Question! Russian language in the inventory.

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Dev#44]
Question about the language, when trying in the inventory to make a folder for example with a Russian name in the server puts information in the format 8B 0X F5 etc the following problems in the server or the client side? Really need to resolve this issue as we have the Russian Grid and not all our users understand when written in English. You can tell that this is not desirable since there will be problems any. But here's the thing Nicky in Russian server perceives good.

http://prntscr.com/f9spy6  As we can see in the first screenshot, at first glance, just not a signed object. But if you click on edit you can see that there are symbols but they are not outputs http://prntscr.com/f9sq4s

**Comment by emperorstarfinder** [comment]
We are aware of issues in the code which causes this.  Fixes are in the pipeline to resolve this issue.  As they are cleared and the required number of core developers sign off they will be pushed to the repository.  We hope to have this resolved before the upcoming release in June.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by LifeGold** [comment]
@emperorstarfinder  https://prnt.sc/fa0siv The problem was solved, she's not on the server side. It is in the client. On the server everything is fine.

**Comment by emperorstarfinder** [comment]
Okay thats good.  Please be sure to open a feature request on the Universe-Viewer-Dev issue tracker so Caseyrae and Briakallista can look into it further.  That way they will know what you did to fix it as well.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by emperorstarfinder** [comment]
User reports this issue is resolved locally.  So closing this ticket.  Please open a new ticket should there be an issue with the base code.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com
