### ISSUE TITLE
[New Feature]: Upgrade script engine

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Dev#8]
### Steps to reproduce

This is a feature issue.

### Expected behaviour

Upgrade the VirtualScript to be on par with either XEngine (from Opensimulator) or Phlox (from Inworldz)

In addition we could potentially offer a new innovative script engine of our own here to.

### Actual behaviour

Not Applicable

### Server configuration

**Operating system**:

Not Applicable

**Web server:**

Not Applicable

**Database:**

Not Applicable

**Virtual Universe version:**

Not Applicable

### Logs

Please make sure that Virtual Universe has made an log-file and include a link to it here

**Comment by emperorstarfinder** [comment]
@BritanyannStarfinder Do you need a branch for this yet?

**Comment by BritanyannStarfinder** [comment]
@emperorStarfinder No not yet.  I am just getting caught up and started on
writing the code for the newly upgraded scripting engine.

For the record:

I have done a preliminary review of the current scripting engine this
morning.  I am not sure what the project leader of WhiteCore-Sim meant
when he told you the scripting engine in its current state is up to date
except for the experience functions.  I am assuming he is referring to the
LSL_Api.

However he is actually incorrect in assuming the scripting engine is up to
date with functional support for scripting language support.  For example
in OSSL_Api both WhiteCore-Sim's DotNetEngine and our VirtualScript do not
yet implement and support functions such as osSetHealth, osGetHealth,
osSetDamage, etc.

I will make a complete list comparing what functions are or are not
currently supported functions in the scripting engine.  In the upgraded
engine I will fix this.


-- 
Britanyann Starfinder
Core Developer
Scripting Engine Developer
Work Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Added to the projects list for Version 1.0.3 so closing here

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
